# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mankepri' do
  use_frameworks!
  pod 'IQKeyboardManagerSwift'
  pod 'DropDown'

  # Pods for Mankepri

  target 'MankepriTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MankepriUITests' do
    # Pods for testing
  end

end
